### ISSUE TITLE
13 dic 2018 - Request slides about Jenkins, JFrog, Conan,...

### ISSUE THREAD

**Issue by jgsogo** [madridccppug/meetups#18]
Let's ping @danimtb, only one slides left: https://madridccppug.github.io/meetups/2018-12-13_Indizen_Bare-metal-programming/ 😸

**Comment by danimtb** [comment]
Here you have the materials (link to slides and link to code repo): https://github.com/danimtb/talks#esp-integraci%C3%B3n-continua-para-dispositivos-embebebidos-usando-jenkins-docker-y-conan
