### ISSUE TITLE
HTML based presentations not being displayed properly

### ISSUE THREAD

**Issue by newlawrence** [madridccppug/meetups#21]
My previously **html-based** submitted presentations are no longer working, [see](https://github.com/newlawrence/Talks/issues/1).

I've already fixed the problem using **Github Pages** and will do a pull request with the updated links as soon as I can.

**Comment by newlawrence** [comment]
Ok, I've been working so long using bare **git** offline at work (no **Github** nor **Gitlab** to help us managing our projects) that I've forgot that my last commit will also be added to the previous pull request 😅.

Right, now #20 also fixes this issue!

**Comment by jgsogo** [comment]
closed via #21
